### ISSUE TITLE
Do we need a Chocolatey package?

### ISSUE THREAD

**Issue by AnthonyMastrean** [AnthonyMastrean/powertab#6]

**Comment by ferventcoder** [comment]
Yes.

**Comment by ferventcoder** [comment]
I'm actually about to create one to support https://github.com/chocolatey/choco/issues/412

**Comment by AnthonyMastrean** [comment]
Whoa, I forgot about this repository. I mostly migrated to PSReadLine. It's slow, but alive. PowerTab seems all but dead now :(

**Comment by ferventcoder** [comment]
Wait, so there is another option for Posh v2?

**Comment by ferventcoder** [comment]
PSReadLine already works great for Chocolatey Tab Expansion in WMF 5 (I tested it this morning). So does the built in tab expansion in Posh v3/4. Now I'm trying to get it working in Posh v2.

**Comment by AnthonyMastrean** [comment]
Oh, I see. I haven't been in the backwards compat scene for a while ;)

**Comment by ferventcoder** [comment]
Sounds nice. :)

On Friday, March 25, 2016, Anthony Mastrean <notifications@github.com>
wrote:

> Oh, I see. I haven't been in the backwards compat scene for a while ;)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/AnthonyMastrean/powertab/issues/6#issuecomment-201609911>
>


-- 

Rob
"Be passionate in all you do"

http://codebetter.com/robreynolds
http://ferventcoder.com
https://twitter.com/ferventcoder
